{% set name = "klayout-gui" %}
{%  set version = "0.27.13" %}
{%    set python = "3.11"   %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  url: https://github.com/KLayout/klayout/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 39c2347ed8aaeb73b7c4c6c806bd25b45b962d6006a26ef88cfa26b8212d3c23
  folder: klayout

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - jom                     # [win]
    - make                    # [not win]

  host:
    - python {{ python }}
    - ruby >2
    - qt-main >=5
    - libpython-static
    - zlib

  run:
    - python {{ python }}
    - ruby >2
    - qt-main >=5
    - ucrt                    # [win]

test:
  commands:
    - klayout -v
  imports:
    - klayout

about:
  home: https://www.klayout.de/
  summary: 'Your Mask Layout Friend'
  description: |
    - View: Fast and accurate viewing of huge layout files
    - Edit: Draw, modify and transform hierarchical layout
    - Generate: Script layout generators, PCells and layout transformation tools
    - Analyze: Search, verify, and measure layout and code analysis scripts
  license: GPL-3.0
  doc_url: https://www.klayout.de/doc.html
  dev_url: https://github.com/KLayout/klayout